### ISSUE TITLE
KeyError: 107

### ISSUE THREAD

**Issue by zafersn** [clebercoutof/mixcell#6]
Hi. I have successfully installed mixcell on my ubuntu 16.04 system. I think mixcell has successfully found my device, but I get an error like this.

I'm using dynamixel ex-106 +, USB2Dynamixel and cm-700.

```
Succeeded to open the port!
Using protocol 1
Succeeded to change the baudrate!
Pinging in ID: 5 
[ID:005] ping Succeeded. Dynamixel model number : 107
Pinging in ID: 6 
[TxRxResult] There is no status packet!
Pinging in ID: 7 
[TxRxResult] There is no status packet!
Succeeded to change the baudrate!
Pinging in ID: 5 
[TxRxResult] There is no status packet!
Pinging in ID: 6 
[TxRxResult] There is no status packet!
Pinging in ID: 7 
[TxRxResult] There is no status packet!
Succeeded to change the baudrate!
Pinging in ID: 5 
[TxRxResult] There is no status packet!
Pinging in ID: 6 
[TxRxResult] There is no status packet!
Pinging in ID: 7 
[TxRxResult] There is no status packet!
Using protocol 2
Succeeded to change the baudrate!
Pinging in ID: 5 
[TxRxResult] There is no status packet!
Pinging in ID: 6 
[TxRxResult] There is no status packet!
Pinging in ID: 7 
[TxRxResult] There is no status packet!
Succeeded to change the baudrate!
Pinging in ID: 5 
[TxRxResult] There is no status packet!
Pinging in ID: 6 
[TxRxResult] There is no status packet!
Pinging in ID: 7 
[TxRxResult] There is no status packet!
Succeeded to change the baudrate!
Pinging in ID: 5 
[TxRxResult] There is no status packet!
Pinging in ID: 6 
[TxRxResult] There is no status packet!
Pinging in ID: 7 
[TxRxResult] There is no status packet!
Traceback (most recent call last):
  File "/home/ubuntu/catkin_ws/src/dynamixel_motor/mixcell/QTCode/mixcell", line 523, in network_search
    self.table_organize(search_result)
  File "/home/ubuntu/catkin_ws/src/dynamixel_motor/mixcell/QTCode/mixcell", line 494, in table_organize
    model = mixcell.model_num[i.model]
KeyError: 107

```

**Comment by zafersn** [comment]
To solve the problem, the model number of ex-106 + in source_code.py is 107.

```
model_num = {44:"AX-12W",12:"AX-12A",28:"EX-106+",24:"RX-24F",28:"RX-28",64:"RX-64",104:"MX-12W",29:"MX-28",54:"MX-64",320:"MX-106"}

change to 

model_num = {44:"AX-12W",12:"AX-12A",107:"EX-106+",24:"RX-24F",28:"RX-28",64:"RX-64",104:"MX-12W",29:"MX-28",54:"MX-64",320:"MX-106"}
```
